# Generated by Django 3.0.7 on 2020-06-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200622_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postitem',
            name='magic_key',
            field=models.CharField(default='OQQGKU', editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='vote_score',
            field=models.IntegerField(),
        ),
    ]
