# Generated by Django 3.0.7 on 2020-06-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200622_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postitem',
            name='magic_key',
            field=models.CharField(default='jvOiKw', editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='vote_score',
            field=models.IntegerField(default=0),
        ),
    ]
