# Generated by Django 3.0.7 on 2020-06-25 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200622_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postitem',
            name='downvotes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='magic_key',
            field=models.CharField(default='IPWmZl', editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='submission_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='upvotes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='postitem',
            name='vote_score',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
